name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        run: npm ci && nx run web_ng:build
      - 
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_FLUTTER_WEATHER }}'
          channelId: live
          projectId: my-flutter-weather
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
