name: Deploy to Firebase Hosting on PR

on: pull_request

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        uses: mansagroup/nrwl-nx-action@v2.0.3
        with:
          targets: build
      - 
        run: npm ci && nx run web_ng:build
      - 
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MY_FLUTTER_WEATHER }}'
          projectId: my-flutter-weather
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
