name: Flutter

on:
  push: 
    branches: 
      - main

  pull_request: 
    branches: 
      - main

jobs: 
  version:
    name: "Generate Mobile Flutter Version Number"
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: "Fetch all history for all tags and branches"
        run: git fetch --prune --depth=10000
      - 
        name: "Install GitVersion"
        uses: gittools/actions/gitversion/setup@v0.9.6
        with:
            versionSpec: '5.x'
      - 
        name: "Use GitVersion"
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.6
      - 
        name: "Create version.txt with nuGetVersion"
        run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > apps/mobile_flutter/version.txt
      - 
        name: "Upload version.txt"
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: apps/mobile_flutter/version.txt

  buildAndroid: 
    name: "Build Android"
    needs: [ version ]
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v1
      - 
        uses: actions/setup-java@v1
        with: 
          java-version: 12.x
      - 
        uses: subosito/flutter-action@v1
        with: 
          channel: stable
          flutter-version: "1.22.5"
      - 
        env: 
          FLUTTER_WEATHER_DEV_LOCAL_SECRET: "${{ secrets.FLUTTER_WEATHER_LOCAL_SECRET }}"
        name: "Decode android local.properties"
        run: "echo $FLUTTER_WEATHER_DEV_LOCAL_SECRET > apps/mobile_flutter/android/local.properties"
      - 
        env: 
          FLUTTER_WEATHER_DEV_ENV_CONFIG_SECRET: "${{ secrets.FLUTTER_WEATHER_ENV_CONFIG_SECRET }}"
        name: "Decode environment config"
        run: "echo $FLUTTER_WEATHER_DEV_ENV_CONFIG_SECRET > apps/mobile_flutter/lib/env_config.dart"
      - 
        name: "Get version.txt"
        uses: actions/download-artifact@v2
        with:
          name: gitversion
      - 
        name: "Read version"
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
      - 
        name: "Flutter get"
        run: "flutter pub get"
      - 
        name: "Flutter build dev"
        run: "flutter build appbundle -t apps/mobile_flutter/lib/main_dev.dart --flavor dev --verbose"

  buildIos:
    name: "Build iOS"
    needs: [ version ]
    runs-on: macos-latest
    steps:
      - 
        uses: actions/checkout@v1
      - 
        uses: actions/setup-java@v1
        with: 
          java-version: 12.x
      - 
        uses: subosito/flutter-action@v1
        with: 
          channel: stable
          flutter-version: "1.22.5"
      - 
        env: 
          FLUTTER_WEATHER_DEV_ENV_CONFIG_SECRET: "${{ secrets.FLUTTER_WEATHER_ENV_CONFIG_SECRET }}"
        name: "Decode environment config"
        run: "echo $FLUTTER_WEATHER_DEV_ENV_CONFIG_SECRET > apps/mobile_flutter/lib/env_config.dart"
      - 
        name: "Get version.txt"
        uses: actions/download-artifact@v2
        with:
          name: gitversion
      - 
        name: "Read version"
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
      - 
        name: "Flutter get"
        run: "flutter pub get"
      - 
        name: "Flutter build dev"
        run: "flutter build ios -t apps/mobile_flutter/lib/main_dev.dart --no-codesign --verbose"